

ployly_symbols = ["square", "star", "diamond", "circle-cross-open", "bowtie-open", "cross-open-dot", "hourglass",
                  "star-triangle-up-open-dot", "x-thin-open", "triangle-right",
                  "diamond-cross", "hexagon-open-dot", "diamond-tall-dot", "hexagon-dot", "line-ew-open",
                  "triangle-ne-dot", "star-triangle-up-dot", "triangle-left-dot", "x-dot", "star-square-open",
                  "hash-open", "circle-open", "triangle-left", "line-ns", "triangle-right-open", "pentagon",
                  "diamond-x", "square-open", "square-x", "square-x-open", "y-right-open",
                  "triangle-sw-open-dot", "x-open", "octagon", "square-cross-open", "triangle-down-open",
                  "line-ne-open", "triangle-sw-open", "triangle-down-open-dot", "asterisk-open", "diamond-tall",
                  "x-open-dot", "diamond-open", "star-triangle-down-dot", "hexagram", "diamond-x-open",
                  "triangle-right-open-dot", "triangle-left-open", "hexagon-open", "triangle-nw-open-dot",
                  "triangle-down", "cross-dot", "triangle-se-open", "y-up-open", "star-dot", "circle", "hexagon2-open",
                  "hexagon", "triangle-se-dot", "cross-open", "star-triangle-down-open-dot", "cross-thin-open",
                  "line-ns-open", "star-square-open-dot", "diamond-cross-open", "triangle-nw-open", "star-square-dot",
                  "y-right", "hash-open-dot", "circle-x-open", "circle-x", "triangle-right-dot", "triangle-nw-dot",
                  "y-left-open", "cross", "hexagram-open", "hash-dot", "hexagram-dot", "diamond-dot", "x",
                  "triangle-down-dot", "diamond-wide", "cross-thin", "triangle-left-open-dot", "diamond-wide-dot",
                  "hexagon2", "diamond-open-dot", "line-ew", "line-nw-open", "star-triangle-down", "hexagram-open-dot",
                  "star-square", "diamond-wide-open-dot", "asterisk", "circle-open-dot", "x-thin", "triangle-ne",
                  "diamond-wide-open", "star-triangle-up", "triangle-up", "triangle-sw",
                  "star-triangle-up-open", "hourglass-open", "triangle-nw", "octagon-dot", "triangle-se-open-dot",
                  "star-diamond", "square-dot", "octagon-open", "triangle-up-open", "triangle-ne-open-dot", "line-nw",
                  "square-open-dot", "triangle-up-open-dot", "pentagon-open-dot", "star-diamond-open",
                  "triangle-sw-dot", "square-cross", "star-diamond-dot", "y-left", "star-diamond-open-dot",
                  "diamond-tall-open", "y-down", "star-open", "bowtie", "pentagon-open",
                  "y-down-open", "star-triangle-down-open", "y-up", "triangle-se", "hexagon2-dot", "line-ne",
                  "pentagon-dot", "diamond-tall-open-dot", "circle-cross", "circle-dot", "triangle-up-dot",
                  "triangle-ne-open", "octagon-open-dot", "star-open-dot", "hash", "hexagon2-open-dot"]
