FROM moinfar/bio-deep-python:tensorflow-py36

COPY installer-gpu.sh /tmp/installer-gpu.sh
RUN sh /tmp/installer-gpu.sh && \
    rm /tmp/installer-gpu.sh

COPY runner.py /app/runner.py
COPY runner.sh /app/runner.sh

WORKDIR /app
ENTRYPOINT ["bash", "runner.sh"]
